create table if not exists users (
    id bigint generated by default as identity primary key,
    tenant_id varchar(64) not null,
    auth_uid varchar(128) not null,
    email varchar(255),
    display_name varchar(255),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    unique (tenant_id, auth_uid)
);

create table if not exists roles (
    id bigint generated by default as identity primary key,
    tenant_id varchar(64) not null,
    name varchar(64) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    unique (tenant_id, name)
);

create table if not exists user_roles (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    unique (user_id, role_id)
);
