spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: process-mgmt-procedures
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: procedures

server:
  port: 8081

app:
  supabase:
    url: ${SUPABASE_URL}
    jwks: ${SUPABASE_JWKS}
