spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: process-mgmt-login
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

server:
  port: 8080
  servlet:
    context-path: /api

app:
  supabase:
    url: ${SUPABASE_URL:}
    jwks: ${SUPABASE_JWKS:}
    service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}
  bootstrap:
    enabled: "false"
    uid: "05c5be39-ade0-4565-b606-62ab1caffaa4"
    tenant-id: "default"
    roles: "admin"
