spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: process-mgmt-login
  sql:
    init:
      mode: never
  datasource:
    url: ${VITE_DB_URL:}
    username: ${VITE_DB_USERNAME:}
    password: ${VITE_DB_PASSWORD:}

app:
  supabase:
    url: ${VITE_SUPABASE_URL:}
    jwks: ${VITE_SUPABASE_JWKS_URL:}
    service-role-key: ${VITE_SUPABASE_SERVICE_ROLE_KEY:}
  bootstrap:
    enabled: "false"
    uid: "05c5be39-ade0-4565-b606-62ab1caffaa4"
    tenant-id: "default"
    roles: "admin"
